import { Space_Grotesk } from "next/font/google";
import "./globals.css";

import Footer from "./shared/Footer";
import Navbar from "./shared/Navbar";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-space-grotesk",
  display: "swap",
});

export const metadata = {
  title: "Gachpala",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={spaceGrotesk.variable}>
      <body className={`font-sans antialiased dark-theme`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
