import { Space_Grotesk } from "next/font/google";
import "./globals.css";

import Footer from "./shared/Footer";
import Navbar from "./shared/Navbar";
import ReduxProvider from "./ReduxProvider";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-space-grotesk",
  display: "swap",
});

export const metadata = {
  title: "Gachpala",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased dark-theme ${spaceGrotesk.variable}`}>
        <ReduxProvider>
          <Navbar />
          {children}
          <Footer />
        </ReduxProvider>
        {/* {children} */}
      </body>
    </html>
  );
}
